# Site settings
title        : "Logan Schexnaydre"
name         : "Logan Schexnaydre"
description  : "PhD candidate in Electrical and Computer Engineering at Michigan Technological University, researching lidar-based perception for energy-efficient autonomous vehicles."
url          : "https://lpschexn.github.io"
baseurl      : ""
repository   : "lpschexn/lpschexn.github.io"
locale       : "en-US"
timezone     : "America/New_York"

# Reading files
include:
  - files
  - _pages

exclude:
  - .github
  - .sass-cache
  - archive
  - Dockerfile
  - docker-compose.yaml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - README.md
  - vendor

keep_files:
  - .git

# Markdown
encoding        : "utf-8"
markdown_ext    : "markdown,mkdown,mkdn,mkd,md"
markdown        : kramdown
highlighter     : rouge
excerpt_separator: "\n\n"

kramdown:
  input        : GFM
  hard_wrap    : false
  auto_ids     : true
  smart_quotes : lsquo,rsquo,ldquo,rdquo

# Output
permalink : "/:categories/:title/"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from
